CREATE TABLE SC_quant (
	id BIGINT UNSIGNED auto_increment NOT NULL COMMENT 'pk',
	evaporating_temp FLOAT NOT NULL COMMENT '蒸发温度',
	delta_t FLOAT NOT NULL COMMENT '温差',
	quant FLOAT NULL COMMENT '修正系数',
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
	update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL,
	is_deleted TINYINT DEFAULT 0 NULL COMMENT '逻辑删除',
	CONSTRAINT cooler_pk PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
COMMENT='工况修正系数';